@hostname = localhost
@port = 3000
@host = http://{{hostname}}:{{port}}

##############################################################
# @no-cookie-jar
# @no-redirect
GET /api/receipt HTTP/1.1
Content-Type: application/json

##############################################################
# @no-cookie-jar
# @no-redirect
GET /api/receipt/8 HTTP/1.1
Content-Type: application/json

##############################################################
# @no-cookie-jar
# @no-redirect
GET /api/receipt/1/8 HTTP/1.1
Content-Type: application/json

##############################################################
# @no-cookie-jar
# @no-redirect
POST /api/receipt/register HTTP/1.1
Content-Type: application/json

{
    "id_usuario": 1,
    "ids_productos": [1, 2, 3, 4, 5]
}
